-- MySQL Script generated by MySQL Workbench
-- 08/17/16 03:21:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema production
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema production
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `production` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dev
-- -----------------------------------------------------
-- SQL_PASS = config['mysql']['password']

-- -----------------------------------------------------
-- Schema dev
--
-- SQL_PASS = config['mysql']['password']
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev` ;
USE `production` ;

-- -----------------------------------------------------
-- Table `production`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `production`.`history` ;

CREATE TABLE IF NOT EXISTS `production`.`history` (
  `type_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  `datetime` INT NOT NULL,
  `all_volume` BIGINT(20) NULL,
  `buy_volume` BIGINT(20) NULL,
  `sell_volume` BIGINT(20) NULL,
  `max_buy` DECIMAL(15,4) NULL,
  `min_sell` DECIMAL(15,4) NULL,
  `buy_stddev` DECIMAL(15,4) NULL,
  `sell_stddev` DECIMAL(15,4) NULL,
  `all_avg` DECIMAL(15,4) NULL,
  `buy_avg` DECIMAL(15,4) NULL,
  `sell_avg` DECIMAL(15,4) NULL,
  `all_count` INT NULL,
  `buy_count` INT NULL,
  `sell_count` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `production`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `production`.`orders` ;

CREATE TABLE IF NOT EXISTS `production`.`orders` (
  `type_id` INT NOT NULL,
  `region_id` BIGINT(20) NOT NULL,
  `station_id` BIGINT(20) NULL,
  `id` VARCHAR(10) NOT NULL,
  `volume_entered` INT NULL,
  `volume` INT NOT NULL,
  `min_volume` INT NULL,
  `buy` TINYINT(1) NOT NULL,
  `price` FLOAT NOT NULL,
  `issued_date` TEXT NOT NULL,
  `duration` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `dev` ;

-- -----------------------------------------------------
-- Table `dev`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`history` ;

CREATE TABLE IF NOT EXISTS `dev`.`history` (
  `type_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  `datetime` INT NOT NULL,
  `all_volume` BIGINT(20) NULL,
  `buy_volume` BIGINT(20) NULL,
  `sell_volume` BIGINT(20) NULL,
  `max_buy` DECIMAL(15,4) NULL,
  `min_sell` DECIMAL(15,4) NULL,
  `buy_stddev` DECIMAL(15,4) NULL,
  `sell_stddev` DECIMAL(15,4) NULL,
  `all_avg` DECIMAL(15,4) NULL,
  `buy_avg` DECIMAL(15,4) NULL,
  `sell_avg` DECIMAL(15,4) NULL,
  `all_count` INT NULL,
  `buy_count` INT NULL,
  `sell_count` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`orders` ;

CREATE TABLE IF NOT EXISTS `dev`.`orders` (
  `type_id` INT NOT NULL,
  `region_id` BIGINT(20) NOT NULL,
  `station_id` BIGINT(20) NULL,
  `id` VARCHAR(10) NOT NULL,
  `volume_entered` INT NULL,
  `volume` INT NOT NULL,
  `min_volume` INT NULL,
  `buy` TINYINT(1) NOT NULL,
  `price` FLOAT NOT NULL,
  `issued_date` TEXT NOT NULL,
  `duration` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
